language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
scala:
  - 2.11.8
# we actually build and run on openjdk8 in production, see scala-jenkins-infra.
# but (as of November 2016) Travis still only supports Oracle Java 8, not OpenJDK 8
jdk:
  - oraclejdk8
notifications:
  email:
    - adriaan.moors@lightbend.com
    - seth.tisue@lightbend.com
cache:
  directories:
  - $HOME/.ivy2/
  - $HOME/.sbt/cache/
  - $HOME/.sbt/boot/
  - $HOME/.sbt/launchers/
env:
  global:
    - GIT_SSH=.travis/ssh_scabot
after_success:
  - openssl aes-256-cbc -K $encrypted_046e6a226c09_key -iv $encrypted_046e6a226c09_iv -in .travis/scabot.pem.enc -out .travis/scabot.pem -d && git push --force scabot@scala-ci.typesafe.com:/home/scabot/scabot master:master

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
